# Generated by Django 5.2.8 on 2026-01-02 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_product_barcode_alter_product_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso')], max_length=3, verbose_name='Tipo de Transacción')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (BOB)')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
